package orchestrator

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"os/exec"
)

// BuildPlan is the parsed, useful subset of `nixpacks plan` output. The
// platform needs exactly three things from it: the detected language family,
// the port the app listens on, and the start command.
type BuildPlan struct {
	Provider   string `json:"provider"`   // e.g. "node", "python", "go"
	StartCmd   string `json:"start_cmd"`  // full command nixpacks would run
	InternalPort int    `json:"internal_port"` // resolved app port
	DetectedLanguage string `json:"detected_language"`
}

// planPayload mirrors just the fields of the nixpacks plan we consume. The
// full JSON is much larger; unmarshalling loosely keeps this robust to
// nixpacks version drift.
type planPayload struct {
	Providers []string `json:"providers"`
	Variables map[string]string `json:"variables"`
	Start     struct {
		Cmd string `json:"cmd"`
	} `json:"start"`
}

// PlanAnalyzes runs `nixpacks plan` in dir and returns the resolved build
// plan. The port may be absent from the plan; detectPort then falls back to
// sensible defaults derived from the provider.
func (o *Orchestrator) PlanAnalyze(ctx context.Context, dir string) (*BuildPlan, error) {
	cmd := exec.CommandContext(ctx, o.cfg.NixpacksBin, "plan", dir)
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	if err := cmd.Run(); err != nil {
		return nil, fmt.Errorf("orchestrator: nixpacks plan failed: %w: %s", err, stderr.String())
	}

	var p planPayload
	if err := json.Unmarshal(stdout.Bytes(), &p); err != nil {
		return nil, fmt.Errorf("orchestrator: parsing nixpacks plan output: %w", err)
	}

	provider := ""
	if len(p.Providers) > 0 {
		provider = p.Providers[0]
	}

	bp := &BuildPlan{
		Provider:         provider,
		StartCmd:         p.Start.Cmd,
		DetectedLanguage: provider,
		InternalPort:     detectPort(provider, p.Variables),
	}
	return bp, nil
}

// BuildImage runs `nixpacks build` for the directory and returns the image tag
// it produced. Output goes to the provided writer (usually the deployment log
// collector so the user can watch build progress).
func (o *Orchestrator) BuildImage(ctx context.Context, dir, name string, progress *bytes.Buffer) (string, error) {
	cmd := exec.CommandContext(ctx, o.cfg.NixpacksBin, "build", "--name", name, dir)
	if progress != nil {
		cmd.Stdout = progress
		cmd.Stderr = progress
	}
	if err := cmd.Run(); err != nil {
		// The image name generated by nixpacks is "name:latest" on success.
		return "", fmt.Errorf("orchestrator: nixpacks build failed: %w", err)
	}
	return name + ":latest", nil
}

// detectPort resolves the internal port for a sandbox container. Preference
// order: explicit PORT/NIXPACKS_PORT variable from the plan, then a provider
// default. Ports here must match what the app actually binds; the platform
// also injects PORT=<port> into the running container so most frameworks
// listen on exactly this value.
func detectPort(provider string, variables map[string]string) int {
	if v := variables["PORT"]; v != "" {
		if n, ok := parsePort(v); ok {
			return n
		}
	}
	if v := variables["NIXPACKS_PORT"]; v != "" {
		if n, ok := parsePort(v); ok {
			return n
		}
	}
	return ProviderDefaultPort(provider)
}

// ProviderDefaultPort returns a sensible default listening port per ecosystem.
func ProviderDefaultPort(provider string) int {
	switch provider {
	case "nodejs", "node":
		return 3000
	case "python", "python3", "flask", "django", "fastapi":
		return 8080
	case "golang", "go":
		return 8080
	case "ruby":
		return 4567
	case "php", "laravel":
		return 8000
	case "static":
		return 80
	case "rust", "cargo":
		return 8000
	default:
		// Conservative default covers most nixpacks providers.
		return 3000
	}
}

func parsePort(s string) (int, bool) {
	var n int
	if _, err := fmt.Sscanf(s, "%d", &n); err != nil || n <= 0 || n > 65535 {
		return 0, false
	}
	return n, true
}